# docker file to run legacy php apps
version: '3.1'

services:
  web:
    image: php:5.6-apache
    container_name: legacy_php_app
    volumes:
      - .:/var/ww/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: legacy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: legacy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
    ports:
      - "3306:3306"